useDotenv: true
service: blog-api

provider:
  name: aws
  region: ap-northeast-1
  stage: dev
  runtime: provided.al2
  memorySize: 512
  environment:
    APP_STORAGE: '/tmp'

custom:
  defaultStage: dev
  profiles:
    dev: sls-itg
    stg: sls-stg
    prd: sls-prd
  secret: ${file(./config/secret.yml)}
  appkey: ${file(./config/appKey.yml)}
  apigwBinary:
    types:
      - multipart/form-data

package:
  exclude:
    - node_modules/**
    - public/storage
    - resources/assets/**
    - storage/**
    - tests/**

functions:
  web:
    handler: public/index.php
    timeout: 28
    layers:
      - ${bref-extra:gd-php-81}
      - ${bref:layer.php-81-fpm}
    events:
      - http: 'ANY /'
      - http: 'ANY /{proxy+}'
    environment:
      APP_KEY: ${self:custom.appkey.APP_KEY}
      DB_PORT: ${self:custom.secret.DB_PORT}
      DB_HOST: ${self:custom.secret.DB_HOST}
      DB_DATABASE: ${self:custom.secret.DB_DATABASE}
      DB_USERNAME: ${self:custom.secret.DB_USERNAME}
      DB_PASSWORD: ${self:custom.secret.DB_PASSWORD}
      MYSQL_ATTR_SSL_CA: ${self:custom.secret.MYSQL_ATTR_SSL_CA}
      LMD_ID: ${self:custom.secret.LMD_ID}
      LMD_SECRET_KEY: ${self:custom.secret.LMD_SECRET_KEY}
      LMD_REGION: ${self:custom.secret.LMD_REGION}
      LMD_BUCKET: ${self:custom.secret.LMD_BUCKET}
      SESSION_DRIVER: ${self:custom.secret.SESSION_DRIVER}
      CACHE_DRIVER: ${self:custom.secret.CACHE_DRIVER}
      APP_NAME: Blog
      APP_ENV: production
      SANCTUM_STATEFUL_DOMAINS: yappi.jp
      SESSION_DOMAIN: .yappi.jp
      LOG_CHANNEL: stderr
      VIEW_COMPILED_PATH: /tmp/storage/framework/views

  artisan:
    handler: artisan
    timeout: 120
    layers:
      - ${bref:layer.php-81-fpm}
      - ${bref-extra:gd-php-81}
      - ${bref:layer.console}
    environment:
      APP_KEY: ${self:custom.appkey.APP_KEY}
      DB_PORT: ${self:custom.secret.DB_PORT}
      DB_HOST: ${self:custom.secret.DB_HOST}
      DB_DATABASE: ${self:custom.secret.DB_DATABASE}
      DB_USERNAME: ${self:custom.secret.DB_USERNAME}
      DB_PASSWORD: ${self:custom.secret.DB_PASSWORD}
      MYSQL_ATTR_SSL_CA: ${self:custom.secret.MYSQL_ATTR_SSL_CA}
      AWS_ID: ${self:custom.secret.AWS_ID}
      AWS_SECRET_KEY: ${self:custom.secret.AWS_SECRET_KEY}
      AWS_REGION: ${self:custom.secret.AWS_REGION}
      AWS_BUCKET: ${self:custom.secret.AWS_BUCKET}
      SESSION_DRIVER: ${self:custom.secret.SESSION_DRIVER}
      CACHE_DRIVER: ${self:custom.secret.CACHE_DRIVER}
      APP_NAME: Blog
      APP_ENV: production
      SANCTUM_STATEFUL_DOMAINS: yappi.jp
      SESSION_DOMAIN: .yappi.jp
      LOG_CHANNEL: stderr
      VIEW_COMPILED_PATH: /tmp/storage/framework/views

plugins:
  - ./vendor/bref/bref
  - ./vendor/bref/extra-php-extensions
